### ISSUE TITLE
Add PETG-HF as a selectable filament type

### ISSUE THREAD

**Issue by Mynymouqe** [bigtreetech/PandaTouch#106]
Hi team - Bambu has added PETG-HF to their filament range. 

You currently can’t select this on the screen manually, and it displays as PETG (not HF).

**Comment by Highlander-bdj** [comment]
This is incredibly annoying.  Can it please be fixed?  It seems like a simple thing to add to the next update.

![image](https://github.com/user-attachments/assets/38cfbd16-119e-4a92-a264-7e93c4d6274f)

**Comment by mytechguyri** [comment]
To expand on this further, this screen needs to pull its data from the Bambu cloud instance, as to what filaments are available, as once you configure a custom filament, while you can select that custom filament in the Bambu Studio application, you cannot select it here on the Panda Touch.   More importantly, when a user has said custom filament loaded, and then selects "unload" on the panda touch, they are presented with an "unknown filament type" screen, and are required to select one of the hard coded filament types in order to proceed with the unload operation, simply because its a custom filament assigned in Bambu Studio, and so the panda touch doesn't recognize it.   If it pulled this data from the Bambu cloud server, it would recognize the filament.

**Comment by bigtreetech** [comment]
@dilixi
