### ISSUE TITLE
Better utilize screen real estate. 

### ISSUE THREAD

**Issue by heelsmj** [bigtreetech/PandaTouch#53]
While printing, the two largest areas of the screen are taken up by the panda, and a picture of the currently selected printer. I understand you mimicked the interface from the X1 carbon however, the fact that you’re not displaying a 3-D image of the model currently being printed just makes the whole interface during the print jumbled.  The relevant information as far as the print progress and what’s being printed is relegated to a tiny font on the bottom. Why not better utilize all the space and make the most relevant information the most prevalent. There is no point in mimicking that interface when you aren’t displaying the same information. Why not better utilize the areas highlighted in red in the photo? I’ve also attached a photo from the XTouxh project. They have a much smaller screen to work with but better utilize the available space. They have a large stop and pause button, and they include the print speed which is not included on the main page of your interface.

![IMG_8447](https://github.com/bigtreetech/PandaTouch/assets/154277123/f342145b-7dab-4dff-8e2a-c8eae3091e80)

![IMG_8445](https://github.com/bigtreetech/PandaTouch/assets/154277123/74006037-f28c-43cc-bda6-7dee3aea260b)

**Comment by philchfree** [comment]
I second this and it would be a departure (improvement) from the bambu offering on the X1. Why can't we have during printing all informations at our disposal, much like the device page of bambu studio rathen than clicking the below screen to access them. I would love to see when printing on the same screen, the fan speeds, the print speed and even an AMS and spool sketch to see which filament is printing. On the left instead of the panda, we can have a small picture of the printer until you can present the actual model which is printing.

**Comment by kurim** [comment]
I agree with you, showing the current printing model like [ha-bambulab](https://github.com/greghesp/ha-bambulab) does already would be great and a very nice improvment.

In HA it looks like this:
![image](https://github.com/bigtreetech/PandaTouch/assets/1880220/4a6ae12a-e70c-4a14-bc45-f7cf8c978ada)

Also bring in the AMS humidity index would be nice.

**Comment by bigtreetech** [comment]
The real estate was reserved for coming features. All will be revealed in August.

**Comment by gpambrozio** [comment]
Would also love this
